export const COUNTRIES = [
    "Deutschland",
    "Österreich",
    "Schweiz",
    "Afghanistan",
    "Ägypten",
    "Åland",
    "Albanien",
    "Algerien",
    "Amerikanisch-Samoa",
    "Amerikanische Jungferninseln",
    "Andorra",
    "Angola",
    "Anguilla",
    "Antarktis",
    "Antigua und Barbuda",
    "Äquatorialguinea",
    "Argentinien",
    "Armenien",
    "Aruba",
    "Ascension",
    "Aserbaidschan",
    "Äthiopien",
    "Australien",
    "Bahamas",
    "Bahrain",
    "Bangladesch",
    "Barbados",
    "Weißrussland",
    "Belgien",
    "Belize",
    "Benin",
    "Bermuda",
    "Bhutan",
    "Bolivien",
    "Bonaire",
    "Bosnien und Herzegowina",
    "Botswana",
    "Bouvetinsel",
    "Brasilien",
    "Britische Jungferninseln",
    "Britisches Territorium im Indischen Ozean",
    "Brunei",
    "Bulgarien",
    "Burkina Faso",
    "Burundi",
    "Ceuta",
    "Chile",
    "Volksrepublik China",
    "Clipperton",
    "Cookinseln",
    "Costa Rica",
    "Curaçao",
    "Dänemark",
    "Diego Garcia",
    "Dominica",
    "Dominikanische Republik",
    "Dschibuti",
    "Ecuador",
    "Elfenbeinküste",
    "El Salvador",
    "Eritrea",
    "Estland",
    "Eswatini",
    "Europäische Gemeinschaft",
    "Europäische Union",
    "Falklandinseln",
    "Färöer",
    "Fidschi",
    "Finnland",
    "Frankreich",
    "Frankreich France métropolitaine",
    "Französisch-Guayana",
    "Französisch-Polynesien",
    "Französische Süd- und Antarktisgebiete",
    "Gabun",
    "Gambia",
    "Georgien",
    "Ghana",
    "Gibraltar",
    "Grenada",
    "Griechenland",
    "Grönland",
    "Guadeloupe",
    "Guam",
    "Guatemala",
    "Guernsey",
    "Guinea",
    "Guinea-Bissau",
    "Guyana",
    "Haiti",
    "Heard und McDonaldinseln",
    "Honduras",
    "Hongkong",
    "Indien",
    "Indonesien",
    "Isle of Man",
    "Irak",
    "Iran",
    "Irland",
    "Island",
    "Israel",
    "Italien",
    "Jamaika",
    "Japan",
    "Jemen",
    "Jersey",
    "Jordanien",
    "Cayman Islands",
    "Kambodscha",
    "Kamerun",
    "Kanada",
    "Kanarische Inseln",
    "Kap Verde",
    "Kasachstan",
    "Katar",
    "Kenia",
    "Kirgisistan",
    "Kiribati",
    "Kokosinseln",
    "Kolumbien",
    "Komoren",
    "Demokratische Republik Kongo",
    "Republik Kongo",
    "Nordkorea",
    "Südkorea",
    "Kosovo",
    "Kroatien",
    "Kuba",
    "Kuwait",
    "Laos",
    "Lesotho",
    "Lettland",
    "Libanon",
    "Liberia",
    "Libyen",
    "Liechtenstein",
    "Litauen",
    "Luxemburg",
    "Macau",
    "Madagaskar",
    "Malawi",
    "Malaysia",
    "Malediven",
    "Mali",
    "Malta",
    "Marokko",
    "Marshallinseln",
    "Martinique",
    "Mauretanien",
    "Mauritius",
    "Mayotte",
    "Mexiko",
    "Mikronesien",
    "Moldau",
    "Monaco",
    "Mongolei",
    "Montenegro",
    "Montserrat",
    "Mosambik",
    "Myanmar",
    "Namibia",
    "Nauru",
    "Nepal",
    "Neukaledonien",
    "Neuseeland",
    "Nicaragua",
    "Niederlande",
    "Niederländische Antillen",
    "Niger",
    "Nigeria",
    "Niue",
    "Nördliche Marianen",
    "Nordmazedonien",
    "Türkische Republik Nordzypern",
    "Norfolkinsel",
    "Norwegen",
    "Oman",
    "Osttimor",
    "Pakistan",
    "Palästina",
    "Palau",
    "Panama",
    "Papua-Neuguinea",
    "Paraguay",
    "Peru",
    "Philippinen",
    "Pitcairninseln",
    "Polen",
    "Portugal",
    "Puerto Rico",
    "Réunion",
    "Ruanda",
    "Rumänien",
    "Russland",
    "Salomonen",
    "Saint-Barthélemy",
    "Saint-Martin",
    "Sambia",
    "Samoa",
    "San Marino",
    "São Tomé und Príncipe",
    "Saudi-Arabien",
    "Schweden",
    "Senegal",
    "Serbien",
    "Serbien und Montenegro",
    "Seychellen",
    "Sierra Leone",
    "Simbabwe",
    "Singapur",
    "Sint Maarten",
    "Slowakei",
    "Slowenien",
    "Somalia",
    "Spanien",
    "Sri Lanka",
    "St. Helena, Ascension und Tristan da Cunha",
    "St. Kitts und Nevis",
    "St. Lucia",
    "Saint-Pierre und Miquelon",
    "St. Vincent und die Grenadinen",
    "Südafrika",
    "Sudan",
    "Südgeorgien und die Südlichen Sandwichinseln",
    "Südsudan",
    "Suriname",
    "Spitzbergen",
    "Syrien",
    "Tadschikistan",
    "Taiwan",
    "Tansania",
    "Thailand",
    "Togo",
    "Tokelau",
    "Tonga",
    "Trinidad und Tobago",
    "Tristan da Cunha",
    "Tschad",
    "Tschechien",
    "Tschechoslowakei",
    "Tunesien",
    "Türkei",
    "Turkmenistan",
    "Turks- und Caicosinseln",
    "Tuvalu",
    "Sowjetunion",
    "Uganda",
    "Ukraine",
    "Ungarn",
    "United States Minor Outlying Islands",
    "Uruguay",
    "Usbekistan",
    "Vanuatu",
    "Vatikanstadt",
    "Venezuela",
    "Vereinigte Arabische Emirate",
    "Vereinigte Staaten",
    "Vereinigtes Königreich",
    "Vietnam",
    "Wallis und Futuna",
    "Weihnachtsinsel",
    "Westsahara",
    "Zaire",
    "Zentralafrikanische Republik",
    "Zypern",
];